services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: bms-backend
    container_name: bms-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend:/var/www

    networks:
      - bms-network

  webserver:
    image: nginx:alpine
    container_name: bms-webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - bms-network

  db:
    image: mysql:8.0
    container_name: bms-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-bms}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_USER: ${DB_USERNAME:-bms}
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - bms-network

  mailpit:
    image: axllent/mailpit
    container_name: bms-mailpit
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - bms-network

  frontend:
    image: node:18-alpine
    container_name: bms-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"
    networks:
      - bms-network

networks:
  bms-network:
    driver: bridge

volumes:
  dbdata:
